# Generated by Django 2.0.7 on 2018-08-03 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=64)),
                ('car_name', models.CharField(max_length=64)),
                ('car_type', models.CharField(max_length=64)),
                ('car_price', models.FloatField()),
                ('car_size', models.IntegerField()),
                ('car_detail', models.CharField(max_length=64)),
                ('car_status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_start_date', models.DateTimeField(blank=True, null=True)),
                ('request_end_date', models.DateTimeField(blank=True, null=True)),
                ('request_pick_up', models.CharField(max_length=64)),
                ('request_drop_off', models.CharField(max_length=64)),
                ('request_status', models.CharField(max_length=64)),
                ('request_approval', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start_date', models.DateTimeField()),
                ('reservation_end_date', models.DateTimeField()),
                ('reservation_pick_up', models.CharField(max_length=64)),
                ('reservation_drop_off', models.CharField(max_length=64)),
                ('reservation_protection', models.CharField(max_length=64)),
                ('reservation_total_price', models.FloatField()),
                ('reservation_status', models.CharField(max_length=64)),
                ('reservation_request', models.CharField(max_length=64)),
                ('reservation_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Car')),
                ('reservation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date_start_date', models.DateTimeField()),
                ('reserved_date_end_date', models.DateTimeField()),
                ('reserved_date_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Car')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='request_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Reservation'),
        ),
    ]
